/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.xml]'
import { Route as ResourceRouteImport } from './routes/resource'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapIndexDotxmlRouteImport } from './routes/sitemap.$index[.]xml'
import { Route as ResourceRidRouteImport } from './routes/resource/$rid'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceRoute = ResourceRouteImport.update({
  id: '/resource',
  path: '/resource',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapIndexDotxmlRoute = SitemapIndexDotxmlRouteImport.update({
  id: '/sitemap/$index.xml',
  path: '/sitemap/$index.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourceRidRoute = ResourceRidRouteImport.update({
  id: '/$rid',
  path: '/$rid',
  getParentRoute: () => ResourceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guide': typeof GuideRoute
  '/resource': typeof ResourceRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/resource/$rid': typeof ResourceRidRoute
  '/sitemap/$index.xml': typeof SitemapIndexDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guide': typeof GuideRoute
  '/resource': typeof ResourceRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/resource/$rid': typeof ResourceRidRoute
  '/sitemap/$index.xml': typeof SitemapIndexDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guide': typeof GuideRoute
  '/resource': typeof ResourceRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/resource/$rid': typeof ResourceRidRoute
  '/sitemap/$index.xml': typeof SitemapIndexDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/guide'
    | '/resource'
    | '/sitemap.xml'
    | '/resource/$rid'
    | '/sitemap/$index.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/guide'
    | '/resource'
    | '/sitemap.xml'
    | '/resource/$rid'
    | '/sitemap/$index.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/guide'
    | '/resource'
    | '/sitemap.xml'
    | '/resource/$rid'
    | '/sitemap/$index.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GuideRoute: typeof GuideRoute
  ResourceRoute: typeof ResourceRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SitemapIndexDotxmlRoute: typeof SitemapIndexDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource': {
      id: '/resource'
      path: '/resource'
      fullPath: '/resource'
      preLoaderRoute: typeof ResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/$index.xml': {
      id: '/sitemap/$index.xml'
      path: '/sitemap/$index.xml'
      fullPath: '/sitemap/$index.xml'
      preLoaderRoute: typeof SitemapIndexDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resource/$rid': {
      id: '/resource/$rid'
      path: '/$rid'
      fullPath: '/resource/$rid'
      preLoaderRoute: typeof ResourceRidRouteImport
      parentRoute: typeof ResourceRoute
    }
  }
}

interface ResourceRouteChildren {
  ResourceRidRoute: typeof ResourceRidRoute
}

const ResourceRouteChildren: ResourceRouteChildren = {
  ResourceRidRoute: ResourceRidRoute,
}

const ResourceRouteWithChildren = ResourceRoute._addFileChildren(
  ResourceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GuideRoute: GuideRoute,
  ResourceRoute: ResourceRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SitemapIndexDotxmlRoute: SitemapIndexDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
